baseURL = "/"
languageCode = "zh-cn"
title = "我的博客"
theme = "PaperMod"

[params]
    # 默认使用系统深色/浅色模式，也可以强制 "light" 或 "dark"
    defaultTheme = "auto" 

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    # 关键就是下面这行，把它改成 "manni" 或者 "friendly" 这种浅色样式
    style = "friendly"
    noClasses = true